"""index source_object cale_originala

Revision ID: 32391cd4bb1d
Revises: 845d3966c9ef
Create Date: 2026-07-28 08:52:03.127703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32391cd4bb1d'
down_revision: Union[str, None] = '845d3966c9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_object_cale_originala'), 'source_object', ['cale_originala'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_object_cale_originala'), table_name='source_object')
    # ### end Alembic commands ###
