"""adauga referinte_xml pe invoice

Revision ID: 752c734010d3
Revises: aa8ddc48f0df
Create Date: 2026-07-28 00:03:53.377285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '752c734010d3'
down_revision: Union[str, None] = 'aa8ddc48f0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('referinte_xml', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'referinte_xml')
    # ### end Alembic commands ###
