"""adauga integrity_alert

Revision ID: 7fb380d7f4c5
Revises: 752c734010d3
Create Date: 2026-07-28 05:41:14.316877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb380d7f4c5'
down_revision: Union[str, None] = '752c734010d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrity_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=15), nullable=False),
    sa.Column('cheie', sa.String(length=255), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('detalii', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('actualizat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('rezolvat_la', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rezolvat_automat', sa.Boolean(), nullable=True),
    sa.Column('rezolvat_de_id', sa.Integer(), nullable=True),
    sa.Column('motiv_rezolvare', sa.Text(), nullable=True),
    sa.CheckConstraint("nivel IN ('info', 'avertisment', 'critic')", name=op.f('ck_integrity_alert_nivel_valid')),
    sa.ForeignKeyConstraint(['rezolvat_de_id'], ['app_user.id'], name=op.f('fk_integrity_alert_rezolvat_de_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrity_alert'))
    )
    op.create_index(op.f('ix_integrity_alert_cod'), 'integrity_alert', ['cod'], unique=False)
    op.create_index('uq_integrity_alert_deschisa', 'integrity_alert', ['cod', 'cheie'], unique=True, postgresql_where=sa.text('rezolvat_la IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_integrity_alert_deschisa', table_name='integrity_alert', postgresql_where=sa.text('rezolvat_la IS NULL'))
    op.drop_index(op.f('ix_integrity_alert_cod'), table_name='integrity_alert')
    op.drop_table('integrity_alert')
    # ### end Alembic commands ###
