"""schema initiala completa

Revision ID: aa8ddc48f0df
Revises: 
Create Date: 2026-07-27 23:31:08.892931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8ddc48f0df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anaf_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('id_descarcare', sa.String(length=50), nullable=False),
    sa.Column('id_incarcare', sa.String(length=50), nullable=True),
    sa.Column('tip_mesaj', sa.String(length=50), nullable=True),
    sa.Column('data_publicare', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_descarcare', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stare', sa.String(length=30), nullable=True),
    sa.Column('expira_la', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anaf_message'))
    )
    op.create_index(op.f('ix_anaf_message_cif'), 'anaf_message', ['cif'], unique=False)
    op.create_index(op.f('ix_anaf_message_id_descarcare'), 'anaf_message', ['id_descarcare'], unique=True)
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('ultima_autentificare', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rol IN ('administrator', 'consultare')", name=op.f('ck_app_user_rol_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('import_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=100), nullable=False),
    sa.Column('tip_sursa', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('mapare', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reguli_curatare', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_profile')),
    sa.UniqueConstraint('denumire', name=op.f('uq_import_profile_denumire'))
    )
    op.create_table('invoice_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=50), nullable=True),
    sa.Column('pozitie_neta', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('calculat_la', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_group'))
    )
    op.create_table('numbering_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif_emitent', sa.String(length=20), nullable=True),
    sa.Column('descriere', sa.String(length=255), nullable=True),
    sa.Column('configuratie', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numbering_rule')),
    sa.UniqueConstraint('cif_emitent', name=op.f('uq_numbering_rule_cif_emitent'))
    )
    op.create_table('reconciliation_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=100), nullable=False),
    sa.Column('definitie', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_rule')),
    sa.UniqueConstraint('denumire', name=op.f('uq_reconciliation_rule_denumire'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moment', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('utilizator_id', sa.Integer(), nullable=True),
    sa.Column('actiune', sa.String(length=50), nullable=False),
    sa.Column('entitate', sa.String(length=50), nullable=True),
    sa.Column('entitate_id', sa.BigInteger(), nullable=True),
    sa.Column('detalii', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['utilizator_id'], ['app_user.id'], name=op.f('fk_audit_log_utilizator_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actiune'), 'audit_log', ['actiune'], unique=False)
    op.create_index(op.f('ix_audit_log_moment'), 'audit_log', ['moment'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('sursa', sa.Text(), nullable=True),
    sa.Column('pornit_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('terminat_la', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stare', sa.String(length=20), nullable=False),
    sa.Column('utilizator_id', sa.Integer(), nullable=True),
    sa.Column('nr_fisiere', sa.Integer(), nullable=False),
    sa.Column('nr_documente', sa.Integer(), nullable=False),
    sa.Column('nr_erori', sa.Integer(), nullable=False),
    sa.Column('anulat_la', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motiv_anulare', sa.Text(), nullable=True),
    sa.CheckConstraint("stare IN ('in_curs', 'terminat', 'terminat_cu_erori', 'anulat')", name=op.f('ck_import_batch_stare_valida')),
    sa.CheckConstraint("tip IN ('scan_local', 'anaf', 'import_extern')", name=op.f('ck_import_batch_tip_valid')),
    sa.ForeignKeyConstraint(['utilizator_id'], ['app_user.id'], name=op.f('fk_import_batch_utilizator_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch'))
    )
    op.create_table('reconciliation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rulat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('nr_potriviri', sa.Integer(), nullable=False),
    sa.Column('nr_exceptii', sa.Integer(), nullable=False),
    sa.Column('nr_ambigue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['reconciliation_rule.id'], name=op.f('fk_reconciliation_run_rule_id_reconciliation_rule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_run'))
    )
    op.create_index(op.f('ix_reconciliation_run_rule_id'), 'reconciliation_run', ['rule_id'], unique=False)
    op.create_table('external_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('profil_id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.Column('numar_brut', sa.String(length=100), nullable=True),
    sa.Column('numar_normalizat', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('total_fara_tva', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tva', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('date_brute', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_external_record_batch_id_import_batch')),
    sa.ForeignKeyConstraint(['profil_id'], ['import_profile.id'], name=op.f('fk_external_record_profil_id_import_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_record'))
    )
    op.create_index(op.f('ix_external_record_batch_id'), 'external_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_external_record_cif'), 'external_record', ['cif'], unique=False)
    op.create_index(op.f('ix_external_record_numar_normalizat'), 'external_record', ['numar_normalizat'], unique=False)
    op.create_table('source_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('continut', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('marime', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('nume_original', sa.Text(), nullable=True),
    sa.Column('cale_originala', sa.Text(), nullable=True),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("tip IN ('zip', 'xml_factura', 'xml_semnatura', 'atasament', 'pdf')", name=op.f('ck_source_object_tip_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_source_object_batch_id_import_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_object'))
    )
    op.create_index(op.f('ix_source_object_batch_id'), 'source_object', ['batch_id'], unique=False)
    op.create_index(op.f('ix_source_object_sha256'), 'source_object', ['sha256'], unique=False)
    # Imutabilitate impusă prin GRANT (cap. 3): rolul de runtime al aplicației
    # (aiefactura_app) primește implicit UPDATE/DELETE prin ALTER DEFAULT PRIVILEGES
    # (db/init/01-app-role.sql) — se retrage explicit doar pentru acest tabel.
    op.execute("REVOKE UPDATE, DELETE ON source_object FROM aiefactura_app")
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('anaf_message_id', sa.Integer(), nullable=True),
    sa.Column('directie', sa.String(length=10), nullable=False),
    sa.Column('cif_emitent', sa.String(length=20), nullable=False),
    sa.Column('cif_beneficiar', sa.String(length=20), nullable=True),
    sa.Column('numar_brut', sa.String(length=100), nullable=False),
    sa.Column('numar_normalizat', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=30), nullable=True),
    sa.Column('numar_numeric', sa.Integer(), nullable=True),
    sa.Column('data_emitere', sa.Date(), nullable=False),
    sa.Column('data_scadenta', sa.Date(), nullable=True),
    sa.Column('tip_document', sa.String(length=50), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('curs', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_fara_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_document', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_de_plata', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('nr_contract', sa.String(length=100), nullable=True),
    sa.Column('nr_comanda', sa.String(length=100), nullable=True),
    sa.Column('perioada_start', sa.Date(), nullable=True),
    sa.Column('perioada_sfarsit', sa.Date(), nullable=True),
    sa.Column('versiune_cius', sa.String(length=255), nullable=True),
    sa.Column('stare', sa.String(length=20), nullable=False),
    sa.Column('eroare_mesaj', sa.Text(), nullable=True),
    sa.Column('eroare_detalii', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xpath_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retras', sa.Boolean(), nullable=False),
    sa.Column('retras_la', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retras_motiv', sa.Text(), nullable=True),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("directie IN ('intrare', 'iesire')", name=op.f('ck_invoice_directie_valida')),
    sa.CheckConstraint("stare IN ('primit', 'parsat', 'normalizat', 'validat', 'indexat', 'eroare')", name=op.f('ck_invoice_stare_valida')),
    sa.ForeignKeyConstraint(['anaf_message_id'], ['anaf_message.id'], name=op.f('fk_invoice_anaf_message_id_anaf_message')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_invoice_batch_id_import_batch')),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_object.id'], name=op.f('fk_invoice_source_object_id_source_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_index(op.f('ix_invoice_batch_id'), 'invoice', ['batch_id'], unique=False)
    op.create_index(op.f('ix_invoice_cif_beneficiar'), 'invoice', ['cif_beneficiar'], unique=False)
    op.create_index(op.f('ix_invoice_cif_emitent'), 'invoice', ['cif_emitent'], unique=False)
    op.create_index(op.f('ix_invoice_data_emitere'), 'invoice', ['data_emitere'], unique=False)
    op.create_index('ix_invoice_dedup_avertizare', 'invoice', ['cif_emitent', 'numar_normalizat', 'data_emitere'], unique=False)
    op.create_index(op.f('ix_invoice_numar_normalizat'), 'invoice', ['numar_normalizat'], unique=False)
    op.create_index(op.f('ix_invoice_stare'), 'invoice', ['stare'], unique=False)
    op.create_table('reconciliation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('external_record_id', sa.Integer(), nullable=True),
    sa.Column('scor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stare', sa.String(length=25), nullable=False),
    sa.Column('diferente', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decizie', sa.String(length=50), nullable=True),
    sa.Column('motiv', sa.Text(), nullable=True),
    sa.Column('utilizator_id', sa.Integer(), nullable=True),
    sa.Column('decis_la', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_record_id'], ['external_record.id'], name=op.f('fk_reconciliation_result_external_record_id_external_record')),
    sa.ForeignKeyConstraint(['group_id'], ['invoice_group.id'], name=op.f('fk_reconciliation_result_group_id_invoice_group')),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], name=op.f('fk_reconciliation_result_run_id_reconciliation_run')),
    sa.ForeignKeyConstraint(['utilizator_id'], ['app_user.id'], name=op.f('fk_reconciliation_result_utilizator_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_result'))
    )
    op.create_index(op.f('ix_reconciliation_result_run_id'), 'reconciliation_result', ['run_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=True),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_attachment_invoice_id_invoice')),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_object.id'], name=op.f('fk_attachment_source_object_id_source_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_index(op.f('ix_attachment_invoice_id'), 'attachment', ['invoice_id'], unique=False)
    op.create_table('invoice_group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('semn', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('semn IN (1, -1)', name=op.f('ck_invoice_group_member_semn_valid')),
    sa.ForeignKeyConstraint(['group_id'], ['invoice_group.id'], name=op.f('fk_invoice_group_member_group_id_invoice_group')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_group_member_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('group_id', 'invoice_id', name=op.f('pk_invoice_group_member'))
    )
    op.create_table('invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('nr_crt', sa.Integer(), nullable=True),
    sa.Column('cod_articol_furnizor', sa.String(length=100), nullable=True),
    sa.Column('cod_articol_client', sa.String(length=100), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('cantitate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('um', sa.String(length=20), nullable=True),
    sa.Column('pret_unitar', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valoare_fara_tva', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cota_tva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('categorie_tva', sa.String(length=10), nullable=True),
    sa.Column('reducere', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('nr_comanda', sa.String(length=100), nullable=True),
    sa.Column('centru_cost', sa.String(length=100), nullable=True),
    sa.Column('xpath', sa.Text(), nullable=True),
    sa.Column('descriere_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('romanian', coalesce(descriere, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_line_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line'))
    )
    op.create_index('ix_invoice_line_descriere_tsv', 'invoice_line', ['descriere_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_invoice_line_invoice_id'), 'invoice_line', ['invoice_id'], unique=False)
    op.create_table('invoice_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('denumire', sa.String(length=255), nullable=True),
    sa.Column('cif_brut', sa.String(length=30), nullable=True),
    sa.Column('cif_normalizat', sa.String(length=30), nullable=True),
    sa.Column('nr_reg_com', sa.String(length=50), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('tara', sa.String(length=2), nullable=True),
    sa.Column('cod_tva', sa.String(length=30), nullable=True),
    sa.Column('cont_bancar', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.CheckConstraint("rol IN ('furnizor', 'client', 'reprezentant_fiscal')", name=op.f('ck_invoice_party_rol_valid')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_party_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_party'))
    )
    op.create_index(op.f('ix_invoice_party_cif_normalizat'), 'invoice_party', ['cif_normalizat'], unique=False)
    op.create_index(op.f('ix_invoice_party_invoice_id'), 'invoice_party', ['invoice_id'], unique=False)
    op.create_table('invoice_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_from', sa.Integer(), nullable=False),
    sa.Column('invoice_to', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=30), nullable=False),
    sa.Column('sursa', sa.String(length=10), nullable=False),
    sa.Column('scor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stare', sa.String(length=15), nullable=False),
    sa.Column('motiv', sa.Text(), nullable=True),
    sa.Column('utilizator_id', sa.Integer(), nullable=True),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("stare IN ('confirmata', 'propusa', 'respinsa')", name=op.f('ck_invoice_relation_stare_valida')),
    sa.CheckConstraint("sursa IN ('xml', 'regula', 'manual')", name=op.f('ck_invoice_relation_sursa_valida')),
    sa.ForeignKeyConstraint(['invoice_from'], ['invoice.id'], name=op.f('fk_invoice_relation_invoice_from_invoice')),
    sa.ForeignKeyConstraint(['invoice_to'], ['invoice.id'], name=op.f('fk_invoice_relation_invoice_to_invoice')),
    sa.ForeignKeyConstraint(['utilizator_id'], ['app_user.id'], name=op.f('fk_invoice_relation_utilizator_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_relation'))
    )
    op.create_index(op.f('ix_invoice_relation_invoice_from'), 'invoice_relation', ['invoice_from'], unique=False)
    op.create_index(op.f('ix_invoice_relation_invoice_to'), 'invoice_relation', ['invoice_to'], unique=False)
    op.create_table('invoice_source_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('creat_la', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_invoice_source_link_batch_id_import_batch')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_source_link_invoice_id_invoice')),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_object.id'], name=op.f('fk_invoice_source_link_source_object_id_source_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_source_link'))
    )
    op.create_index(op.f('ix_invoice_source_link_invoice_id'), 'invoice_source_link', ['invoice_id'], unique=False)
    op.create_table('tax_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('cota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('categorie', sa.String(length=10), nullable=True),
    sa.Column('baza', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_tax_summary_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_summary'))
    )
    op.create_index(op.f('ix_tax_summary_invoice_id'), 'tax_summary', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_summary_invoice_id'), table_name='tax_summary')
    op.drop_table('tax_summary')
    op.drop_index(op.f('ix_invoice_source_link_invoice_id'), table_name='invoice_source_link')
    op.drop_table('invoice_source_link')
    op.drop_index(op.f('ix_invoice_relation_invoice_to'), table_name='invoice_relation')
    op.drop_index(op.f('ix_invoice_relation_invoice_from'), table_name='invoice_relation')
    op.drop_table('invoice_relation')
    op.drop_index(op.f('ix_invoice_party_invoice_id'), table_name='invoice_party')
    op.drop_index(op.f('ix_invoice_party_cif_normalizat'), table_name='invoice_party')
    op.drop_table('invoice_party')
    op.drop_index(op.f('ix_invoice_line_invoice_id'), table_name='invoice_line')
    op.drop_index('ix_invoice_line_descriere_tsv', table_name='invoice_line', postgresql_using='gin')
    op.drop_table('invoice_line')
    op.drop_table('invoice_group_member')
    op.drop_index(op.f('ix_attachment_invoice_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_reconciliation_result_run_id'), table_name='reconciliation_result')
    op.drop_table('reconciliation_result')
    op.drop_index(op.f('ix_invoice_stare'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_numar_normalizat'), table_name='invoice')
    op.drop_index('ix_invoice_dedup_avertizare', table_name='invoice')
    op.drop_index(op.f('ix_invoice_data_emitere'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_cif_emitent'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_cif_beneficiar'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_batch_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_source_object_sha256'), table_name='source_object')
    op.drop_index(op.f('ix_source_object_batch_id'), table_name='source_object')
    op.drop_table('source_object')
    op.drop_index(op.f('ix_external_record_numar_normalizat'), table_name='external_record')
    op.drop_index(op.f('ix_external_record_cif'), table_name='external_record')
    op.drop_index(op.f('ix_external_record_batch_id'), table_name='external_record')
    op.drop_table('external_record')
    op.drop_index(op.f('ix_reconciliation_run_rule_id'), table_name='reconciliation_run')
    op.drop_table('reconciliation_run')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_audit_log_moment'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actiune'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('reconciliation_rule')
    op.drop_table('numbering_rule')
    op.drop_table('invoice_group')
    op.drop_table('import_profile')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_anaf_message_id_descarcare'), table_name='anaf_message')
    op.drop_index(op.f('ix_anaf_message_cif'), table_name='anaf_message')
    op.drop_table('anaf_message')
    # ### end Alembic commands ###
